---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  #- name: ubuntu-12.04
  #- name: ubuntu-14.04
  #- name: centos-6.4
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[selinux::permissive]
      # # - recipe[timezone-ii]
      # # - recipe[apt]
      - recipe[build-essential]
      - recipe[yum]     
      - recipe[postgresql::server]
      - recipe[postgresql::client]
      - recipe[galaxy]
      - recipe[apache2]
      - recipe[apache2::mod_proxy]
      - recipe[apache2::mod_proxy_http]
      - recipe[galaxy-httpproxy-cookbook]
      - recipe[galaxy-environment-test]
    attributes:
      python:
        install_method: "source"
        version: "2.7.9"
        # 2.7.8
        # 74d70b914da4487aa1d97222b29e9554d042f825f26cb2b93abd20fdda56b557  Python-2.7.8.tgz
        #checksum: "74d70b914da4487aa1d97222b29e9554d042f825f26cb2b93abd20fdda56b557"
        # 2.7.9
        # c8bba33e66ac3201dabdc556f0ea7cfe6ac11946ec32d357c4c6f9b018c12c5b  Python-2.7.9.tgz
        checksum: "c8bba33e66ac3201dabdc556f0ea7cfe6ac11946ec32d357c4c6f9b018c12c5b"
        #prefix_dir: "/home/vagrant"
        prefix_dir: "/usr/local/python2.7.9"
      tz: "Asia/Tokyo"
      postgresql:
        password: 
           postgres: "ilovethispassword"
      build-essential:
        compile_time: true 
      galaxy:
        user: "galaxy"
        group: "galaxy"
        home: "/usr/local/galaxy"
        #admin_users: "example@example.com"
        #master_api_key: "changeit"
        reference: "latest_2014.08.11"
        overwrite_run_sh: true

        tool_dependency_dir: "./tool_dependency_directory"
        db:
          type: "postgresql"
          hostname: "127.0.0.1"
          databaseusername: "galaxy"
          databasepassword: "galaxy"
          admin:
            username: "postgres"
            password: "ilovethispassword"

