---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'


platforms:
  #- name: ubuntu-12.04
  - name: ubuntu-14.04
    driver:
      vagrantfile_erb: Vagrantfile.erb
    run_list:
      - role[ubuntu1404]
      - recipe[apache2::mod_authz_host]
      - recipe[apache2::mod_access_compat]
    attributes:
      apt:
        compile_time_update: true
      build-essential:
        compile_time: true
      ubuntu:
        mirror_site_url: "http://ftp.jaist.ac.jp/pub/Linux/ubuntu/"
        version: "14.04"
        need_deb_src: false
        need_update: true

  #- name: centos-6.4
  - name: centos-6.5
    driver:
      vagrantfile_erb: Vagrantfile.erb
    run_list:
      - role[centos65]
    attributes:
      galaxy_http_proxy:
        galaxy_conf: "galaxy.conf.erb"
  - name: centos-7.0
    driver:
      vagrantfile_erb: Vagrantfile.erb
    run_list:
      - role[centos70]
      - recipe[apache2::mod_authz_host]
      - recipe[apache2::mod_access_compat]

suites:
  - name: default
    run_list:
      - recipe[selinux::permissive]
      # # - recipe[timezone-ii]
      # # - recipe[apt]
      - recipe[build-essential]
      #- recipe[yum]     
      - recipe[postgresql::server]
      - recipe[postgresql::client]
      - recipe[galaxy@0.6.7]
      - recipe[apache2]
      - recipe[apache2::mod_proxy]
      - recipe[apache2::mod_proxy_http]
      - recipe[galaxy-httpproxy@0.3.1]
      #- recipe[galaxy-environment-test]
    attributes:
      python:
        #install_method: "source"
        #version: "2.7.9"
        ## 2.7.8
        ## 74d70b914da4487aa1d97222b29e9554d042f825f26cb2b93abd20fdda56b557  Python-2.7.8.tgz
        ##checksum: "74d70b914da4487aa1d97222b29e9554d042f825f26cb2b93abd20fdda56b557"
        ## 2.7.9
        ## c8bba33e66ac3201dabdc556f0ea7cfe6ac11946ec32d357c4c6f9b018c12c5b  Python-2.7.9.tgz
        #checksum: "c8bba33e66ac3201dabdc556f0ea7cfe6ac11946ec32d357c4c6f9b018c12c5b"
        ##prefix_dir: "/home/vagrant"
        #prefix_dir: "/usr/local/python2.7.9"
      tz: "Asia/Tokyo"
      postgresql:
        password: 
           postgres: "ilovethispassword"
      build-essential:
        compile_time: true 
      galaxy:
        user: "galaxy"
        group: "galaxy"
        home: "/usr/local/galaxy"
        #admin_users: "example@example.com"
        #master_api_key: "changeit"
        reference: "latest_2014.08.11"
        overwrite_run_sh: true
        overwrite_fetch_eggs_py: true

        tool_dependency_dir: "./tool_dependency_directory"
        db:
          type: "postgresql"
          hostname: "127.0.0.1"
          databaseusername: "galaxy"
          databasepassword: "galaxy"
          admin:
            username: "postgres"
            password: "ilovethispassword"

